Fix build of tests with -fno-common
Starting from gcc-10 and clang-11, "-fcommon" is switched to
"-fno-common" by default. This changed code generator to emit
globals without explicit initializer from .bss (via COMMON symbol type)
to .data (via DEFAULT symbol type), which leads to mutltiple definitions
error:

CMakeFiles/icd_loader_test.dir/test_platforms.c.o:(.bss+0x0): multiple
definition of `ret_val'
CMakeFiles/icd_loader_test.dir/test_kernel.c.o:(.bss+0x0): first defined
here
CMakeFiles/icd_loader_test.dir/test_program_objects.c.o:(.bss+0x0):
multiple definition of `ret_val'
CMakeFiles/icd_loader_test.dir/test_kernel.c.o:(.bss+0x0): first defined
here
CMakeFiles/icd_loader_test.dir/test_sampler_objects.c.o:(.bss+0x0):
multiple definition of `ret_val'
CMakeFiles/icd_loader_test.dir/test_kernel.c.o:(.bss+0x0): first defined
here
CMakeFiles/icd_loader_test.dir/test_cl_runtime.c.o:(.bss+0x0): multiple
definition of `ret_val'
CMakeFiles/icd_loader_test.dir/test_kernel.c.o:(.bss+0x0): first defined
here
CMakeFiles/icd_loader_test.dir/test_clgl.c.o:(.bss+0x0): multiple
definition of `ret_val'
CMakeFiles/icd_loader_test.dir/test_kernel.c.o:(.bss+0x0): first defined
here
CMakeFiles/icd_loader_test.dir/test_image_objects.c.o:(.bss+0x0):
multiple definition of `ret_val'
CMakeFiles/icd_loader_test.dir/test_kernel.c.o:(.bss+0x0): first defined
here

This patch added "static" storage class specifier to "ret_val"
variables, so they are not shared between different translation units.
To reproduce the error with older compiler, add "-fno-common" to compile
flags explicitly (-DCMAKE_C_FLAGS="-fno-common")

Signed-off-by: Alexey Sachkov <alexey.sachkov@intel.com>