OpenCL-SDK base changes (#160)
* pkgconfig stub

* OPENCL_ICD_LOADER_HEADERS_DIR to CMAKE_PREFIX_PATH

* Remove duplicate include(GNUInstallDirs)

* Update Windows builds

* Add LIBRARY DESTINATION to install

* Disable defunct tests

* Fix before_script in appveyor

* Fix dir name

* Change to absolute path in CMAKE_PREFIX_PATH

* Change path to solution

* Simplify exported target name

* Uniform GNUInstallDirs location (before install)

* Avoid having to copy DLLs

* Remove travis

* Adopt GH Actions from Headers repo

* Change syntax

* Fix Headers source dir

* Specify PREFIX_PATH for headers consumption

* relative dir for checkout v2

* Only one type of include/link syntax

* WIP

* Fixing per-target include and link

* ISO C forbids ‘return’ with void function

* comparison of unsigned expr < 0 is always false

* unused parameter ‘input_headers’

* error C2055

* CL_TARGET_OPENCL_VERSION=300

* Register ICD through env var for testing

* Intel(R) CPU Runtime for OpenCL(TM) Applications

* Disable crashing code

* Disable presubmit.yml

* Fix for GCC

* Try conditional symbolic arg

* Remove ISO conformance from Linux builds

* trade error for warning

* Fix syntax error

* again

* Proper inversion of lang extensions

* fix ctest cwd

* Change cwd specification

* Delete consumption tests

* Test Windows

* Install header project in Windows

* Don't build tests of headers

* Add CMAKE_PREFIX_PATH

* Update cwd spec

* Parallel Ninja build spec

* fix stage predicate

* Remove /WX

* Disable language extension less build

* debug find

* probe env vars

* trace expand

* Don't search system paths

* explicit CONFIG

* Probe cmake version

* No system path for OpenCLHeaders

* no semi-colon

* NO_CMAKE_SYSTEM_PATH

* dir

* dir in the right place

* backslashes

* Checkout with names

* backslashes while buildling headers

* fix checkout

* but really

* --output-on-failure

* Print logs on error

* Allow fail for Windows builds

* list build dir

* Multi-config friendly test launch

* Remove  --trace-expand --debug-find

* List Release dir

* show before testing

* BUILD_SHARED_LIBS=OFF on Windows

* Force OpenCL only to be static

* No force static lib

* allow only tests to fail

* Remove debug messages

* Test macOS

* install OpenCL-Headers on macOS

* Add missing PREFIX_PATH

* --debug-find

* Fix typo

* Remove debug find

* Enable all platforms

* Initial CI stub

* Update base image version (git)

* Shallow clone OpenCL-Headers

* Fix OpenCL-Headers clone

* Bump CMake minimum version

* Use gcc instead of g++

* Specify CMAKE_PREFIX_PATH

* Bump image version

* Don't look for a C++ compiler

* Only look for a C++ compiler when necessary

* Enabling layers doesn't require adding new include paths

* Conume test stub

* Add bare test

* Fix set_tests_properties invocation

* Fix consume test paths

* Target OpenCL version should not leak to consumers

* Specify stub implementation path

* Consume tests --output-on-failure

* Fix multi-config stub driver path

* Wire up sdk-style consumption test

* Fix syntax error in echoed CMake script

* Correct path to OpenCLHeaders install location

* Try literal path

* Fix set_tests_properties invocation

* Bump image version

* Add support for building as add_subdirectory

* Specify CL_TARGET_OPENCL_VERSION

* Remove dead code

* Add newlines at the end of file

* /MT -> /MD

* Capitalization problem (discovered by Mate)

* Updated build instructions

* Reflect image changes in GA

* Semi-colon error

* Fix 32-bit linux builds

* Retire Appveyor

* Break OSes into their own yml

* Remove syntax error

* Move env scope

* Create CMake folder

* Fix source path on consume tests

* Remove semi-colon

* Fix consume build dir

* Handle URL discrepancy

* Wildcard instead of shell expand

* Add arch flags

* WIP

* Fix matrix dim name

* Install multilib fog clang

* Add sudo to apt-add-repository

* fix config arg for CTest

* Don't handle CRT errors

* Load release stub driver

* Install multilib for cmake-minimum Clang too

* Windows improvements

* Dereference executable paths correctly

* Fix CMAKE_URL deref

* PWSH env deref

* WIP

* Remove v140

* Look for ninja

* Install Ninja

* test vcvarsall

* Search for vcvarsall.bat

* WIP

* 64-bit VS

* Allow failure on Windows test (empty stub log)

* Proper CTest invocation

* Test MacOS

* Enable all platforms

* Remove presubmit

* Test updated Headers install

* Test updated Headers install in all cases

* Enable CMake latest

* Fixed typo

* Re-add OPENCL_ICD_LOADER_HEADERS_DIR

* Unconditionally compile OpenCLON12 loader sources

* Redocument OPENCL_ICD_LOADER_HEADERS_DIR

* Resolve -pedantic warning

* No incomplete init

* Try full on warnings

* Update .github/workflows/linux.yml

Implementation is ISO friendly now on Linux

Co-authored-by: Brice Videau <brice.videau@gmail.com>

* Install using OPENCL_ICD_LOADER_HEADERS_DIR

Co-authored-by: Brice Videau <brice.videau@gmail.com>

* Loadable ICDs for testing on Windows

Use registry entries instead of env vars

Co-authored-by: Brice Videau <brice.videau@gmail.com>

* Test strict conformance on Windows

* Remove GitLab CI

* Re-enable ISO conforming builds

Co-authored-by: Brice Videau <brice.videau@gmail.com>

* Revert repo redirection to KhronosGroup

Co-authored-by: Ivan Siutsou <ivan@streamhpc.com>
Co-authored-by: Brice Videau <brice.videau@gmail.com>